### ISSUE TITLE
Swift: NSArray(ofColorsWithColorScheme: , for: , flatScheme: ) does not build

### ISSUE THREAD

**Issue by deanq** [VAlexander/Chameleon#10]
`let kColorTheme = NSArray(ofColorsWithColorScheme: ColorSchemeComplementary, for: UIColor.redColor(), flatScheme: true)` will never pass Xcode for Swift. It keeps blocking errors:
- Expected expression in list of expressions
- Expected ',' separator

Is `for:` a forbidden parameter keyword in Swift?

**Comment by VAlexander** [comment]
Hi guys! Been super busy these past few weeks, but I definitely want to look into this. I haven't dwelled into swift yet, but something tells me @deanq may be on to something. If anyone wants to pitch in or submit a pull request, I'd be happy to accept it. In the mean time I'll try to figure this out! Thanks for using Chameleon and I hope it's been useful :smiley:

**Comment by VAlexander** [comment]
This issue has been fixed in 21230b0. Shoutouts to @sfader! :+1:
