### ISSUE TITLE
Unexpected results with GradientColor

### ISSUE THREAD

**Issue by sadaqata** [VAlexander/Chameleon#13]
[[UINavigationBar appearance] setBarTintColor:GradientColor(UIGradientStyleLeftToRight,
                                                                    CGRectMake(0, 0, 1024, 64),
                                                                    (@[FlatGreenDark, FlatGreen]))];

The result is a dark gray navigation bar.

**Comment by VAlexander** [comment]
Hi @sadaqata.

I may be wrong, but it seems like you may be attempting to perform this in a view controller. Just to make sure, try setting the ```barTintColor``` to something basic such as: ```[UIColor redColor];``` If you still see a dark gray navigation bar (I'm assuming this is the default ```navigationBar``` color), then my suspicions may be correct.

Instead what you want to do is set this either in your AppDelegate or ```UINavigationController``` subclass. I admit that Chameleon isn't as flexible when it comes to ```UIAppearance``` (Working on the best way to make this happen for the next update), so I would recommend creating a ```UINavigationController``` subclass file, if you haven't already and do the following there:

``` Objective-C
[[UINavigationBar appearance] setBarTintColor:GradientColor(UIGradientStyleLeftToRight, CGRectMake(0, 0, 1024, 64), (@[FlatGreenDark, FlatGreen]))];
```

I've tried this in both a navigation controller subclass, and the app delegate file, and can confirm that it is working. Let me know if this works for you.
