### ISSUE TITLE
Chameleon Shorthand in Swift

### ISSUE THREAD

**Issue by imdevin567** [VAlexander/Chameleon#14]
Is it possible to use the chameleon shorthand in Swift? It doesn't seem to be autocompleting in Xcode.

I installed the latest version using CocoaPods and added Chameleon/Chameleon.h to my bridging header.

**Comment by VAlexander** [comment]
Supp @imdevin567

Unfortunately, Objective-C macros don't really have a counterpart in Swift. Instead, [Apple recommends using global constants in place of simple macros and functions and generics for more complicated stuff](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html#//apple_ref/doc/uid/TP40014216-CH8-XID_20). In our case, the best thing would be to use a combination of global constants and functions.

I've been pretty busy these past few weeks to dwell too deeply into Swift (or for that matter convert Chameleon over to swift). However if you want, I could add an optional ```Constants.swift``` file to the project in the next week or so. What do you think? If you rather not wait, here's a quick way to get started.

You can create a ```Constants.swift``` file and convert all the macros that take in an input(s) to swift functions. Here's an example:
###### Objective-C:
``` objective-c
#define rgb(r,g,b) [UIColor colorWithRed:r/255.0f green:g/255.0f blue:b/255.0f alpha:1.0]
```
###### Swift:
``` swift
func rgb(r:CGFloat, g:CGFloat, b:CGFloat) -> UIColor {
    return UIColor(red:r/255.0, green:g/255.0, blue:b/255.0, alpha: 1.0)
}
```
From the usage side of things, they both look pretty identical.
###### Objective-C:
``` objective-c
self.view.backgroundColor = rgb(165, 198, 59);
```
###### Swift:
``` swift
view.backgroundColor = rgb(165, 198, 59)
```

You can then convert the rest of the macros, such as ```FlatLime```, to global constants:
###### Objective-C:
``` objective-c
#define FlatLime rgb(165, 198, 59)
```
###### Swift:
``` swift
let FlatLime = rgb(165, 198, 59)
```

Same as before, usage is pretty much the same.
###### Objective-C:
``` objective-c
self.view.backgroundColor = FlatLime;
```
###### Swift:
``` swift
view.backgroundColor = FlatLime
```

Let me know if this helps. :sunglasses:
