### ISSUE TITLE
Retina gradient rendering for supported devices

### ISSUE THREAD

**Issue by alist** [VAlexander/Chameleon#18]
I was having a 1-pixel wrap around from bottom to top for certain UIColors generated by 
```
+ (UIColor *)colorWithGradientStyle:(UIGradientStyle)gradientStyle
```

I resolved it locally by having the UIGraphics context use the current screen's scale
```
UIGraphicsBeginImageContextWithOptions(backgroundGradientLayer.bounds.size,NO, [UIScreen mainScreen].scale);
```

Take a look at this diff:
https://github.com/VAlexander/Chameleon/compare/master...alist:master#diff-d75ec200ce59d4e5a90a77e80cc5af5d

**Comment by VAlexander** [comment]
Aah. Smart. Definitely an improvement. Thanks @alist! :sunglasses:
